# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "zivoosh-testing-terragrunt-dev-terraform-state"
    dynamodb_table = "zivoosh-testing-terragrunt-dev-terraform-locks"
    encrypt        = true
    key            = "dev/vpc/terraform.tfstate"
    region         = "us-east-1"
  }
}
