apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: "{{ .Release.Name }}-ec2nc"
{{- if .Values.ec2nc.annotations }}
  annotations:
{{- range $key, $value := .Values.ec2nc.annotations }}
    {{ $key }}: {{ quote $value }}
{{- end }}
{{- end }}
spec:
{{- if ne .Values.ec2nc.ephemeral_storage "" }}
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: {{ .Values.ec2nc.ephemeral_storage }} 
        volumeType: gp3
        encrypted: true
{{- end }}
  amiFamily: {{ .Values.ec2nc.amiFamily | quote }}
  role: {{ .Values.ec2nc.karpenter_role | quote}}
  subnetSelectorTerms:
  - tags:
      {{ .Values.ec2nc.karpenter_tag }}: "{{ .Values.ec2nc.karpenter_value }}"
  securityGroupSelectorTerms:
  - tags:
      {{ .Values.ec2nc.karpenter_tag }}: "{{ .Values.ec2nc.karpenter_value }}"
  tags:
    {{ .Values.ec2nc.karpenter_tag }}: "{{ .Values.ec2nc.karpenter_value }}"
  amiSelectorTerms:
  - alias: al2023@latest
